# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- develop

variables: 
  solutionDir: 'Zeem\Zeem\'
pool:
  vmImage: windows-latest

steps:
- script: dotnet build
  displayName: 'Build Database Project'
  workingDirectory: $(solutionDir)


