# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- develop

pool:
  vmImage: windows-latest

steps:
- task: MSBuild@1
  inputs:
    solution: '**/*.sqlproj'
    msbuildArchitecture: 'x64'
    configuration: 'release'

